apiVersion: v1
kind: ConfigMap
metadata:
  name: workstation-config
  namespace: workstation
data:
  PORT: "4000"
  AUTH_SERVICE_URL: "http://auth-service:4001"
  TASK_SERVICE_URL: "http://task-service:4002"
  ANALYTICS_SERVICE_URL: "http://analytics-service:4003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:4005"
  REDIS_URL: "redis://redis:6379"
  MONGO_URI: "mongodb://mongodb:27017/workstation"
  NEXT_PUBLIC_API_BASE_URL: "http://api-gateway:4000"
  NEXT_PUBLIC_WS_BASE_URL: "ws://realtime-service:4004"
