apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mongodb.yaml
  - redis.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - task-service.yaml
  - analytics-service.yaml
  - notification-service.yaml
  - realtime-service.yaml
  - frontend.yaml
